---
  - name: install and configure gitlab-runner
    hosts: TEST_SERVER
    become: yes
    gather_facts: false  
    tasks:
      
      - name: add rep
        ansible.builtin.command: 
          cmd: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh 
          

      - name: update cache
        ansible.builtin.apt:
          update_cache: yes

      - name: install gitlab-runner
        ansible.builtin.apt:
          name: gitlab-runner
          state: present
