---
- name: update and upgrade package
  hosts: TEST_SERVER
  become: yes 
  tasks:
    - name: update package
      ansible.builtin.apt:
        update_cache: yes

    - name: upgrade package
      ansible.builtin.apt:
        upgrade: dist

    - name: Install packages
      ansible.builtin.apt:
        name:
          - git
          - curl
          - vim
          - htop
        state: present

    - name: remove unnecessery packages
      ansible.builtin.apt:
        autoremove: yes

