---
  - name: update cache
    ansible.builtin.apt:
      update_cache: yes

  - name: install apt-transport-https
    ansible.builtin.apt:
      name: apt-transport-https
      state: present

  - name: install java
    ansible.builtin.apt:
      name: default-jdk
      state: present

